version: '2'
services:
  vertx-selenium-server:
    build: ./dist
    ports: 
      - "8082:8082"
    volumes:
      - "./cache:/home/cache"
  selenium:
    image: "selenium/standalone-chrome"
    ports:
      - "4444:4444"
    extra_hosts:
       - "www.nextprot.org:10.0.30.90"
       - "api.nextprot.org:10.0.30.90"
       - "www.google-analytics.com:127.0.0.1"
